# Generated by Django 5.1.2 on 2024-10-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mvs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
